# Generated by Django 5.2.12 on 2026-03-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('forecast_web', 'Forecast (web form)'), ('risk_web', 'Risk (web form)'), ('forecast_api', 'Forecast (API)'), ('risk_api', 'Risk (API)'), ('iris_api', 'Iris lab (API)')], db_index=True, max_length=32)),
                ('region_id', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mlapp_analy_created_fdbcbd_idx')],
            },
        ),
    ]
